### ISSUE TITLE
It should not be possible to add entries with an empty citekey

### ISSUE THREAD

**Issue by omangin** [pubs/pubs#113]
See original comment from @pmarkaide in #87.

>If I can add to the discussion, at very least pubs should avoid adding bib entries without citekeys as a minimal field.
> I can add this without an error or even warning:
```
  @Manual{,
    title = {R: A Language and Environment for Statistical Computing},
    author = {{R Core Team}},
    organization = {R Foundation for Statistical Computing},
    address = {Vienna, Austria},
    year = {2017},
    url = {https://www.R-project.org/},
  }
#the output from citation() in R
```

**Comment by omangin** [comment]
Cannot actually reproduce the issue. @pmerkaide, which version of `pubs` and `bibtexparser` are you using. The example above is not even parsed for me.

**Comment by pmarkaide** [comment]
Sorry for the delay. I see that you've made a commit and close the issue, but I assume the info is still relevant:

```
bibtexparser              0.6.2
pubs                          0.7.0
``` 
Both installed through pip.

As you can't even parse the example, I've again added the bib entry above, just to be sure. The bib is added "correctly":

```
(CONDA_ENV) USER@HOST $ pubs add bib.bib
added to pubs:
[] Team, R Core "R: A Language and Environment for Statistical Computing" (2017) 
```
as you see, I've conda environment installed. If you need full package list, just ask :)

**Comment by omangin** [comment]
Indeed, I can reproduce it now with these versions.

The bug is however fixed in the latest git version. The fix will be in the next release but you can already install the latest development version (see [https://github.com/pubs/pubs#installation](https://github.com/pubs/pubs#installation)).
