### ISSUE TITLE
manual bib/citekey edition

### ISSUE THREAD

**Issue by pmarkaide** [pubs/pubs#115]
Even after careful examination during data entry, I've found some errors in some of my bib entries. How should I edit those safely? I can't see the cache so I don't know how will impact my manual editions.

Also related, how I should edit the citekey itself? if the citekey has the `AUTHORYEAR` format, and multiple entries are added for the same year and author, pubs conveniently add a letter (`AUTHORYEARa`). The "problem" is that pubs add the letter in the same order as they are entered. I found more convenient to add the extra letter following the publication date order.  Is there any way to edit the citekey and apply the change to all pubs internals?

**Comment by benureau** [comment]
Dear @pmarkaide,
You should use the `pubs edit <citekey>` command. This will prompt you to edit the bibtex file, including the citekey. Pubs will take care of updating all necessary information. You should not edit the file directly, as if you change the citekey, the name of the file and the metadata needs to be changed as well.

You can reorder the citekeys, but for the moment, you can edit only one entry at a time. That means that, you may need to edit some entry multiple time to avoid collisions during the reordering.

**Comment by pmarkaide** [comment]
I completely miss that command :$. I was in the middle of a paper reading session and I stop my self before editing bib file, "first ask or you will regret later". Later in the weekend, I post the issue, without testing first all commands. I'll test everything before next time :)

I've tested both `pubs edit` and `pubs edit -m` and everything seems fine. The latter is very useful as I would like to change doc filename for book chapter entries. 

Thanks!

**Comment by omangin** [comment]
Be careful that the document is *not* moved automatically when you edit it's name in the metadata file! If your document is handled by pubs (i.e. in your pubs repository) then it is named after the citekey. If it's outside, then you would have to also move the corresponding file.

Please let us now by opening an other issue if these do not cover your usage so that we can think about adding corresponding features.
