### ISSUE TITLE
Removes the use of the `link` customization

### ISSUE THREAD

**Issue by omangin** [pubs/pubs#119]
Using such link format does not seem to be standard and does not have effect any more since bibtexparser uses the `url` field by default.

Removing the url parsing would go in the direction of being format agnostic for better compatibility. To replace it, a method could be added to try to interpret the `url` field as an url (trying different formats), for example to be able to automatically download documents.

See also https://github.com/sciunto-org/python-bibtexparser/issues/188.

Any though?

**Comment by benureau** [comment]
What was the rationale behind the `link` customization?

The link customization is broken currently. It duplicate the entry and each edit will add a comma, ending up with something like this:
```
link = {http://dx.doi.org/10.1007/s00422-012-0514-6,,, http://dx.doi.org/10.1007/s00422-012-0514-6},
```
And yes, using `link` is problematic, as we are actually removing the `url` field from the the bibtex (just verified that). We should absolutely not do that. So yes, I agree, we should remove the link. And probably provide a way to merge all entries (whilst removing all the commas?).

**Comment by omangin** [comment]
> What was the rationale behind the link customization?

Apparently it was assuming some format with potentially several links and for each, an actual link, a protocol, and a link displayed text. The customization was parsing it and outputting a list of dictionaries to represent the data. The code in pubs was relying on this structured information at write time but this was not used anywhere else.

What I suggest is to be agnostic of the link/url format (only relying on bibtexparser to rename links to urls). This means just keeping whatever is in the value as it is. We may in the future want to use the link information for example to download a paper automatically. What I suggest in this case is, instead of relying on an expected format, to just try to extract urls from the field value (in most of the case it will just be the value itself or a comma split of the value with some stripping) and try downloading for any of these urls (or alternatively try a set of predefined methods for expected formats).

> And yes, using link is problematic, as we are actually removing the url field from the the bibtex (just verified that).

What part is removing the `url` field? This need to be fixed (as well as the comma issue you mentions above).

**Comment by benureau** [comment]
> What part is removing the url field? This need to be fixed (as well as the comma issue you mentions above).
Well it does not anymore with the new version. But a few commits ago, the `url` field would be renamed `link` by bibtexparser.

**Comment by benureau** [comment]
> What I suggest is to be agnostic of the link/url format (only relying on bibtexparser to rename links to urls). This means just keeping whatever is in the value as it is. We may in the future want to use the link information for example to download a paper automatically. What I suggest in this case is, instead of relying on an expected format, to just try to extract urls from the field value (in most of the case it will just be the value itself or a comma split of the value with some stripping) and try downloading for any of these urls (or alternatively try a set of predefined methods for expected formats).

I agree with that totally. Url processing should be just-on-time. Closing this now, as it seems to be resolved, if I am not mistaken.

**Comment by omangin** [comment]
> Closing this now, as it seems to be resolved, if I am not mistaken.
Not completely, the code still expect the customization to be there in some place. I will fix it.
