### ISSUE TITLE
Adding the document with a Unicode character in the author's name fails: 'ascii' codec can't encode character u'\xf6' in position 34: ordinal not in range(128)

### ISSUE THREAD

**Issue by yurivict** [pubs/pubs#143]
```
$ pubs add -D 10.1103/PhysRevB.50.17953 -d blchl1994.pdf 
error: 'ascii' codec can't encode character u'\xf6' in position 34: ordinal not in range(128)
```

The document can be downloaded with this command:
```
wget "http://sci-hub.tw/downloads/abee/blchl1994.pdf?download=true" -O blchl1994.pdf
```

**Comment by yurivict** [comment]
This is fixed in the latest revision.

**Comment by benureau** [comment]
@yurivict: yeah, we did some work on unicode a few commits ago. This issue reminds me we need to release a new version soon, and perhaps release bug fixes releases more often.

**Comment by yurivict** [comment]
So far I just moved the FreeBSD port to the current revision.
But yes, more frequent release would be great!
