### ISSUE TITLE
"add" command ignores doc_add=move

### ISSUE THREAD

**Issue by hpdeifel** [pubs/pubs#144]
Steps to reproduce:

1. Set `doc_add = move` in `.pubsrc`
2. Run `pubs add -D foo -d some.pdf`

**Expected behavior**: `some.pdf` is moved to the document directory.

**Actual result**: `some.pdf` is copied to the document directory.

**Comment by benureau** [comment]
Hi @hpdeifel,

Sorry for the delay, quite busy right now.
Indeed. I noticed that on my end quite a while ago, but I thought it was limited to my configuration. I'll look into it shortly.
