### ISSUE TITLE
Add references with arXiv ID

### ISSUE THREAD

**Issue by joe-antognini** [pubs/pubs#145]
It would be very convenient if papers could be added with their arXiv ID the same way that they can be added with their DOI since many arXiv papers don't have DOIs:

```
$ pubs add --arxiv math/0211159
```

or 

```
$ pubs add -X math/0211159
```

The way I would see this working is that if the arXiv paper already has a DOI (which can be obtained from the arXiv API), we would use the DOI API call.  If not (e.g., if the paper is unpublished), then we would generate a bibtex entry.

One downside of this feature is that if a paper is later published and gets a DOI, the user would have to manually add the updated information (DOI, journal, etc.) or else the reference information will be stale.  (Perhaps another feature would be a command like `pubs arxiv-update` or something that would check to see if the arXiv paper now has a DOI associated with it.)

I have a WIP that I can submit as a PR if the pubs team thinks this is a good idea.

**Comment by benureau** [comment]
Hi @joe-antognini. Indeed, with the increase prevalence of arXiv, I have been thinking about doing that for quite a while. As an added bonus, with arXiv, we could arrange for the pdf to be downloaded as well. Do submit your work in progress, I think this could be a great addition to pubs.

**Comment by benureau** [comment]
Closed by #146, #155.
