### ISSUE TITLE
Use stubs for tests in `test_apis.py`

### ISSUE THREAD

**Issue by joe-antognini** [pubs/pubs#147]
The tests in `tests/test_apis.py` make actual HTTP requests.  This should be avoided since it means the tests can't be run if the user doesn't have internet or if one of the servers is down.  (It also leads to slow tests.) Instead we should use stubs that simply return the results of these HTTP requests.

To deal with the possibility that the returned format might change, we could add a test which is ordinarily skipped that makes sure that the various API servers are returning the expected results.  This test could be run every now and again just to make sure the API calls haven't changed.

I'd be happy to take care of this, but I might not be able to get to it until next weekend.

**Comment by omangin** [comment]
Good point @joe-antognini! I am in favor of indeed keeping a skipped-by-default test with the actual request. We could set up a periodic task on Travis for that. So please contribute a solution!

I am not sure what is the best way for getting control on whether network dependent tests are run or not. We might consider using test suites for that or a conditional skip based on some environment variable. Do you have any opinion?

**Comment by benureau** [comment]
Closed by #155.
