### ISSUE TITLE
`pubs add` does not recognise saved file on Windows

### ISSUE THREAD

**Issue by epogrebnyak** [pubs/pubs#169]
I save a .bib file in editor, but get this response:

```
λ pubs add
prompt: Bibfile not edited. Edit again ? Yes/no:
```

**Comment by benureau** [comment]
Hum... the thing is, we never actually tested it on Windows (we also use Travis for testing, which does not support Windows yet https://docs.travis-ci.com/user/multi-os/). Which editor are you using? If you're willing to go and look at the problem, you're more than welcome to submit a pull request.

A workaround is to create the bibtex file and then use `pubs add file.bib`. But that won't help much with commands such as `pubs edit`.

Also, are you using the windows command line or the WSL https://docs.microsoft.com/en-us/windows/wsl/install-win10 ? It might work on the later.

**Comment by epogrebnyak** [comment]
Thank you for the answer - could you also provide some entry points on
where to look for modules responsible for adding the entry? Willing to look
at implementation and suggest windows fix.

I use native cmd.exe and configured Sublime (subl.exe) as an editor.

Does pubs expect some sort of callback from an editor or just check the
state of temporary file?

пн, 10 сент. 2018 г., 12:26 Fabien C. Y. Benureau <notifications@github.com

**Comment by benureau** [comment]
As noted in the configuration file, you need to ensure that GUI editor wait for you to finish editing (by closing the file), before returning. This is done by invoking `subl --wait` under macOS or Linux (https://www.sublimetext.com/docs/3/osx_command_line.html). This would explain the problem. I could not find the equivalent for Windows. Two things to try:

- finding a similar flag for the `subl.exe` command
- using a terminal editor (the `edit` editor ?) to check if this is indeed the reason for the problem.

**Comment by benureau** [comment]
@epogrebnyak: did you manage to solve it?

**Comment by benureau** [comment]
@epogrebnyak: closing this issue for now. Do not hesitate to reopen if necessary.
