### ISSUE TITLE
Better config

### ISSUE THREAD

**Issue by omangin** [pubs/pubs#18]
- Safe config load, See comment on 48ad7e9b6973e9e4f26063c8ea6ad5734645da18.
- Clean config code and remove access as global variable.

**Comment by 73** [comment]
Garding feat/new_config: 
I'd like to point out that the need to place a comma in an empty list (or a list with one element) seems counter intuitive ... Default config reads:
```
[plugins]
# comma-separated list of the plugins to load
active = ,
```
If one wants to add a plugin it has to read `active = plugin,` to run though `conf.check_conf()`. If the comma is missing one gets an `AssertionError`.
--73

**Comment by 73** [comment]
And the comment in https://github.com/pubs/pubs/blob/master/pubs/config/spec.py#L14 should really specify available options.
--73

**Comment by 73** [comment]
Sry. Im just going through that file... 
https://github.com/pubs/pubs/blob/master/pubs/config/spec.py#L42 does not exists yet.      
https://github.com/pubs/pubs/blob/master/pubs/config/spec.py#L44  why is black available but white is not? (I have a dark background).
--73

**Comment by humm** [comment]
Too very good issues.

**Comment by humm** [comment]
Remaining issues are being handled by #44, closing this.
