### ISSUE TITLE
Append a line of text to 'pubs note'

### ISSUE THREAD

**Issue by dvklopfenstein** [pubs/pubs#200]
Thank you so much for these great tools.

Is there a way to append a text line into the note file? I am hoping to be able to do something like this:

```
$ pubs note schwikowski2000network -a 'Append this line to notes'
```

or 
```
cat info.txt | pubs note schwikowski2000network
```

**Comment by benureau** [comment]
Hi @dvklopfenstein. Thank you.

No, there is no such `-a` functionality at the moment, but it should not be too hard to add it. That seem indeed that would allow more scripting of pubs note. Piping won't work reliably, as it would need to be adapted to the specific user-defined editor in the config.

**Comment by beuerle** [comment]
You could achieve this functionality by defining an `alias` in your `pubsrc`, for example:

```config
...
[alias]
append = !~/.pubs/.scripts/append.sh $@
...
```

and then have a little helper script (here `~/.pubs/.scripts/append.sh`):

```zsh
#!/usr/bin/env zsh

dir=~/.pubs/notes
ext=md

key=$1
shift

echo "$@"
echo "$@" >> $dir/$key.$ext
```

> ```$ pubs note schwikowski2000network -a 'Append this line to notes'```

The syntax is then similar, but does not need any quotation marks:

```zsh
$ pubs append schwikowski2000network This is a phenomenal paper.
$ cat ~/.pubs/schwikowski2000network.md
This is a phenomenal paper.
```

(obviously, adjust the notes directory and the file extension accordingly)

**Comment by benureau** [comment]
That's quite ingenious.

**Comment by dvklopfenstein** [comment]
Thanks for the script, it still would be useful to add a `-a` argument in the same spirit as `git commit's `-m` arg:

```
$ git commit file.txt -m 'Commit the changes in file.txt'
```

Pubs version:
```
$ pubs note Varoquaux_2018 -a 'Large error bars compromise conclusions'
```


The `-a` argument would be familiar to command-line users and well-documented through the help mechanism.

**Comment by dvklopfenstein** [comment]
Thank you for these great tools. The append is now fully incorporated into my daily work flow.
