### ISSUE TITLE
Add multiple tags to a bib entry using with one run of 'pubs tag'

### ISSUE THREAD

**Issue by dvklopfenstein** [pubs/pubs#202]
Thank you very much for your excellent tools. They are in my daily pipeline now. It was so easy to adopt them.

Would it be possible to add functionality to ***pubs tag*** such that multiple tags could be added in one run of the command, like this:

```
$ pubs tag Wu_2013 tagname1 tagname2
```
Currently, I must do this:
```
$ pubs tag Wu_2013 tagname1
$ pubs tag Wu_2013 tagname2
```

If I try to add more than one tag in one run of ***pubs tag***, I see this:
```
$ pubs tag Wu_2013 tagname1 tagname2
usage: pubs [-c FILE] [--force-colors] [-v] [-h]
            {init,conf,add,rename,remove,list,edit,tag,statistics,doc,note,export,import,websearch,url,append}
            ...
pubs: error: unrecognized arguments: tagname2
```

**Comment by ksunden** [comment]
you can do 
`pubs tag Wu_2013 tagname1+tagname2`

**Comment by dvklopfenstein** [comment]
That is great! Thank you. Closing this issue...
