### ISSUE TITLE
Unknown bibtex key "software"

### ISSUE THREAD

**Issue by nbiederbeck** [pubs/pubs#210]
the `software` key in bibtex files is not reconized. Editing the file fails (using `pubs edit`) and when editign by hand, exporting fails with following error:
```
error: ('U', 'n', 'a', 'b', 'l', 'e', ' ', 't', 'o', ' ', 'd', 'e', 'c', 'o', 'd', 'e', ' ', 'b', 'i', 'b', 't', 'e', 'x', ' ', 'f', 'o', 'r', ' ', 'p', 'a', 'p', 'e', 'r', ' ', 'P', 'a', 'p', 'e', 'r', '.')
```

**Comment by benureau** [comment]
@nbiederbeck: Sorry for the delay. That's problematic indeed. Will fixed it ASAP.

**Comment by benureau** [comment]
Hi again. Looking into it, "software" does not appear to be a standard bibtex entry type. I have never dealt with those entry before. Could you provide me more information about how it is defined? pubs relies on `bibtexparser` to parse bibtex, so changing the supported bibtex grammar would have to be done there.
