### ISSUE TITLE
Multiple library directories

### ISSUE THREAD

**Issue by cristobaltapia** [pubs/pubs#211]
Hi,

I have been trying pubs for a few weeks and I like it so far. There is one think though I would like to ask: would you consider having multiple libraries defined in the configuration file? I think, that this would be a nice addition, since it allows to separate some publications by topics. For example, I work in one field, but also like to read papers from different fields sometimes, so it would be nice to have them in different folders. Another example would be to have one library only for standards.

I imagine it could be defined in a new block in the configuration file like this:

```ini
[library-main]
pubsdir = ~/.pubs/main
docsdir = ~/.pubs/main/doc

[library-standards]
pubsdir = ~/.pubs/standards
docsdir = ~/.pubs/standards/doc

```

It would be similar to what is implemented in papis. Would that be something you would be interesting to have in pubs?

**Comment by benureau** [comment]
@cristobaltapia: that's a nice idea. I don't know how much refactoring it would entail. Besides having different directories for different libraries, how would the user experience differ? It would also make the add command more complex, as it would need additional functions to specify the library to add a new paper too. And it would need to be tested with pretty much every other aspect of pubs. As it is now, I am not sure that it is worth the effort in implementing, refactoring, testing, and additional UI/conf complexity. What would be the real advantages that cannot be achieved with tags?

**Comment by cristobaltapia** [comment]
@benureau: it would certainly require some refactoring. However, for the current users nothing should dramatically change in the user experience, as one library would be default (the one already defined in the current config file):
```ini
[main]
pubsdir = ~/.pubs
docsdir = ~/.pubs/doc
```
Or, with the new configuration options:
```ini
[main]
default-lib=library-main

[library-main]
pubsdir = ~/.pubs/main
docsdir = ~/.pubs/main/doc

[library-standards]
pubsdir = ~/.pubs/standards
docsdir = ~/.pubs/standards/doc
```

Both notations would be allowed.

To interact with the other libraries one would do something like:
```bash
pubs --lib library-standards add ...
```
That is how it is done in papis. (If you are asking yourself 'why you don't use papis then?' It is mainly due to the format of the database, since papis stores everything in yaml files and I like the pubs approach with bibfiles better ;) .)

The difference with using tags would be that I could share a repo with a colleague without having to share all papers I have ever read (the same for the colleague). That would be the main difference for me.

I am glad that you like the idea in principle. I could try to implement this and post the different ideas here. However, since my principal job is to do research (and try to finish my PhD) I cannot promise speed here :P .

**Comment by benureau** [comment]
So first, speed is not an issue. As described in the readme, science comes first, so the issues may get resolved slowly. 

I was wondering more about your problem. Would you consider using two different repositories? Pubs does support configurations files (and it should be documented more). If you create an alias of the sort `alias pubsstd = "pubs -c path/to/config/for/standards"`, you should be able to do almost everything that you want. You will not be able to do combined searches out of the box, but even that you could script. I think at this point it may be preferable rather than refactor pubs. Adding complexity make adding future features more expensive. What do you think?

**Comment by cristobaltapia** [comment]
I think that is a super good solution! I agree with you about not adding more complexity to the code. This should cover all I need actually.
I will try this and report back.
Thanks

**Comment by benureau** [comment]
Closing this issue, follow up in #214 if help is needed.
