### ISSUE TITLE
Make number of author before 'et al.' a configuration parameter

### ISSUE THREAD

**Issue by cristobaltapia** [pubs/pubs#212]
I am using pubs together with wofi [0] (like rofi but for wayland), so I basically use the `list` command to get all the papers and then search through them for authors' names or whatever. The problem is that not all authors are present in the string if the paper has more than three authors due to the 'et al.' notation. This number is hard-coded [here](https://github.com/pubs/pubs/blob/master/pubs/pretty.py#L29).

Would you consider making this number a configuration parameter? It should be a fairly easy change.

[0] https://hg.sr.ht/~scoopta/wofi

**Comment by benureau** [comment]
Yes, that should be a parameter in the configuration, and that should be easy to do. We could even have `0` as a special value saying that `et al.` should never be used.

**Comment by cristobaltapia** [comment]
Yes, the `0` parameter is a good idea (much better that what I was thinking: just writing 99 :P )

**Comment by benureau** [comment]
Would not have worked with this one: https://arxiv.org/abs/1109.4897v4 :)

**Comment by cristobaltapia** [comment]
haha no, that one would have not worked. I hope the list of names don't count for the maximum number of pages allowed.

**Comment by cristobaltapia** [comment]
Thanks! I was literally thinking about this yesterday, but saw no update. And then I get the Email notification :P
It is working as expected for me.
