### ISSUE TITLE
Pubs checking the wrong directory when using the 'init' command

### ISSUE THREAD

**Issue by cristobaltapia** [pubs/pubs#215]
While playing with the multi-configuration setup I came across a small bug. This is the setup:

1. A configuration file (standards.conf) is created with a different directory defined for the `pubsdir` and `docsdir`
```ini
[main]

pubsdir = ~/Literature/standards
docsdir = ~/Literature/standards/doc
...
```
2. Create the directory for the alternative library (`mkdir ...`)
3. Initialize the pubs directory
```bash
$ pubs -c ~/.config/pubs/standards.conf init
Initializing pubs in /home/tapia/.pubs
```
4. The directory is initialized in ~/.pubs :open_mouth: 
5. Also, the standards.conf file is changed, and now looks like this:
```ini
[main]

pubsdir = /home/tapia/.pubs
docsdir = /home/tapia/.pubs/doc
...
```

This means that pubs is not considering the directory defined in the parameters `pubsdir` and `docsdir`. Can you reproduce this?

**Comment by benureau** [comment]
Yes. You are not supposed to create the configuration file. Only edit it. Look at the `pubs init --help`:
```
§ pubs init --help
usage: pubs init [-h] [-p PUBSDIR] [-d DOCSDIR]

optional arguments:
  -h, --help            show this help message and exit
  -p PUBSDIR, --pubsdir PUBSDIR
                        directory where to put the pubs repository (if none, ~/.pubs is used)
  -d DOCSDIR, --docsdir DOCSDIR
                        path to document directory (if not specified, documents willbe stored in /path/to/pubsdir/doc/)
```
It should also have the option for the configuration file, I have to fix the help dialogs...
Of course, having that documented in the readme could help.

**Comment by cristobaltapia** [comment]
Ok. I thought the '--config' would apply to each command. Not a big deal, but would be nice to have it. (very low priority I would say, since it is not a command you use the whole time :P )

**Comment by benureau** [comment]
No, the `--config` does apply to every command, but because we can load plugins that add commands depending on the config, we have to process it before the commands are loaded, and because of this, it does not appear in the help dialog of the command. I have to fix that.
Do specify the `--config` argument, else pubs will default to the default config path.

**Comment by cristobaltapia** [comment]
Ah, alright, now I understand. Thanks.
