### ISSUE TITLE
Support for biblatex entry types

### ISSUE THREAD

**Issue by kentdobias** [pubs/pubs#218]
`biblatex` defines [an expanded class](https://en.wikibooks.org/wiki/LaTeX/Bibliography_Management#Entry_and_field_types_in_.bib_files) of entry types for BiBTeX. Right now `pubs` fails to add any entry with one of those types, or edit an existing entry to have one of those types.

Here is an example:
```
% cat collection.bib
@collection{Geometric_phases,
 title = {Geometric phases in physics},
 editor = {Shapere, Alfred and Wilczek, Frank},
 year = {1989},
 series = {Advanced Series in Mathematical Physics},
 volume = {5},
 publisher = {World Scientific},
 isbn = {9789971506216}
}

% pubs add collection.bib 
error: no valid entry found in the provided data:  @collection{Geometric_phases,
 title = {Geometric phases in physics},
 editor = {Shapere, Alfred and Wilczek, Frank},
 year = {1989},
 series = {Advanced Series in Mathematical Physics},
 volume = {5},
 publisher = {World Scientific},
 isbn = {9789971506216}
}

```

It would be nice to have support for these entry types.

**Comment by benureau** [comment]
This is the same issue to #210. python-bibtexparser (https://github.com/sciunto-org/python-bibtexparser), used by pubs, does not currently supports them, and is not actively developed anymore. We will probably need to switch to another parser. I am currently looking at pybtex (https://pybtex.org/). If you know other with Python API that support this, do propose them.
