### ISSUE TITLE
Document linking not working with  `doc add`

### ISSUE THREAD

**Issue by loicreynier** [pubs/pubs#219]
`pubs add -d <doi> -d <file> -L` creates a link to the document in the meta file but the linking option is not working on my system in `pubs doc add -L <doc> <citekey>`. It copies the file to `docsdir`.

**Comment by benureau** [comment]
Hi @loicreynier,
Thanks for the issue report. Indeed, there was a typo in the argument parser. Reopen if it still does not work with the latest master.
