### ISSUE TITLE
Cannot link a document

### ISSUE THREAD

**Issue by nevillejackson** [pubs/pubs#221]

**Comment by nevillejackson** [comment]
pubs doc add --link docname bibentry
puts a copy in .pubs/doc, not a link
is it trying to do a hardlink or a softlink?
i made sure .pubs/doc is on same device as the doc file in case it is trying to do hardlink
i would prefer a softlink

**Comment by omangin** [comment]
Thanks @nevillejackson for reporting this. Indeed, it is supposed to use a softlink. I will try to reproduce your issue.

**Comment by nevillejackson** [comment]
Hi Olivier,Thanks.  I can script an example if you need it.regardsNevilleSent from Samsung tablet.
-------- Original message --------From: Olivier Mangin <notifications@github.com> Date: 4/5/20  8:41 am  (GMT+10:00) To: pubs/pubs <pubs@noreply.github.com> Cc: Neville Jackson <nanddjackson@bigpond.com>, Mention <mention@noreply.github.com> Subject: Re: [pubs/pubs] Cannot link a document (#221) 
Thanks @nevillejackson for reporting this. Indeed, it is supposed to use a softlink. I will try to reproduce your issue.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/pubs/pubs/issues/221#issuecomment-623194647",
"url": "https://github.com/pubs/pubs/issues/221#issuecomment-623194647",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by omangin** [comment]
@nevillejackson I just updated my comment above.
