### ISSUE TITLE
[FR] auto completion in fish

### ISSUE THREAD

**Issue by rien333** [pubs/pubs#230]
Hi! First of all, thanks for the project. I've been only been using it briefly so far, but it seems interesting and powerful playing around with it a bit. 

However, I noticed that there is no autocomplete for fish shell. Is this an error on my side?  If not, I would gladly do some coding to get it working (provided it's nothing too complicated)

**Comment by benureau** [comment]
Hi. No, fish shell autocomplete has not been backed in the project. If you are willing to do it, we would welcome the contribution.

**Comment by rien333** [comment]
You can get auto-completion for fish pretty easily, the `argcomplete` documentation lists [https://kislyuk.github.io/argcomplete/#fish-support](how) .
