### ISSUE TITLE
[Question] Use `command` functions from a python script with git plugin

### ISSUE THREAD

**Issue by cristobaltapia** [pubs/pubs#239]
Hi, I am working on a wofi [0] plugin for pubs, to easily manage my reference from a simple GUI. I already did this with a mix of bash and python scripts [1], but now I am rewriting it in pure python, so that it works a bit faster. For adding and editing references I thought of directly using the functions defined in the `commands` module, e.g. for editing I do `from pubs.commands.edit_cmd import command as edit_cmd` and use that function directly. That works wonderfully. The only problem is that the git plugin seems not to be working. What is that that I am missing for the plugin to work? As I understand, that should automatically happen once the `ModifyEvent()` is called at the end of the `command` function.

Any help on this is welcomed :)

[0] https://hg.sr.ht/~scoopta/wofi
[1] https://github.com/cristobaltapia/wofi-pubs

**Comment by benureau** [comment]
@cristobaltapia: That's a very nice project! It probably would be useful for pubs to output the results of commands as xml or similar so it can be fed to such downstream interfaces.

For the git plugin problem, can you be more specific? How do you know it does not work? Any error output? What have you tried? What is your configuration?

**Comment by benureau** [comment]
Btw, the way you proceed seems to bypass a lot of the work done in the `pubs_cmd.py` file, such as:
https://github.com/pubs/pubs/blob/d11f44327617e9a69c27bf0d8c196bfd2f13330a/pubs/pubs_cmd.py#L88

We may need to refactor the code a bit if you want to use it as an API.

**Comment by cristobaltapia** [comment]
> @cristobaltapia: That's a very nice project! It probably would be useful for pubs to output the results of commands as xml or similar so it can be fed to such downstream interfaces.

That could be a good idea. However, now I am implementing it in python and access directly to the `Repository` object containing all the references, so I can print each line with the format I need. (I still haven't uploaded that branch, as it is not ready.)

> For the git plugin problem, can you be more specific? How do you know it does not work? Any error output? What have you tried? What is your configuration?

There is no error. The edit works correctly, but if I `cd` to the repository and make `git status` one can see that the changes are not comited.

> Btw, the way you proceed seems to bypass a lot of the work done in the pubs_cmd.py file, such as:

That is probably an important line that I was missing! Thanks for pointing that out. I just assumed that the function `pubs.config.load_conf()` would take care of that. I will try to consider that in my code and see how far I can get :)

**Comment by cristobaltapia** [comment]
So, what I am currently doing is basically the following:

```py
from pubs import plugins
from pubs.commands.edit_cmd import command as edit_cmd
from pubs.config import load_conf
from pubs.uis import _ui as pubs_ui
from pubs.uis import init_ui

class PubsArgs:
    """Dummy class to store arguments needed for the pubs commands."""
    def __init__(self):
        self.meta = None
        self.citekey = None

conf = load_conf("path/to/conf")
conf['main']['edit_cmd'] = "nvim" # A simple example, in reality I open a new terminal with nvim
conf.write()
init_ui(conf)
plugins.load_plugins(conf, pubs_ui)

args = PubsArgs()
args.citekey = "Einstein_1905"
edit_cmd(conf, args)
```

This opens the _bibfile_ with `nvim` in order to edit it. However the `PostCommandEvent` is not executing, even though the plugins should be loaded.

**Comment by cristobaltapia** [comment]
I figured it out. I had to call `events.PostCommandEvent().send()` after calling the `edit_cmd()` function. Now it works :)
