### ISSUE TITLE
Tilde only expanded sometimes

### ISSUE THREAD

**Issue by dotlambda** [pubs/pubs#249]
My `.pubsrc` contains
```
[main]
pubsdir = ~/.pubs
```
Most commands (`add`, `doc`, `edit`, ...) work fine. When I use `pubs note foobar` however, pubs is trying to create a file at `./~/.pubs/notes/foobar.txt`.

**Comment by benureau** [comment]
Thanks for the report. It should be fixed with e6d0754, which should be merged in master soon.
