### ISSUE TITLE
Support field name "type"

### ISSUE THREAD

**Issue by dotlambda** [pubs/pubs#252]
Biblatex has an entry type `thesis` where you "use the `type` field to specify the type of thesis."

Pubs removes that field when specified, leaving an invalid entry because `type` is a required field for `thesis`. I think
https://github.com/pubs/pubs/blob/89429a8c24d0aef444de614f2a102feeb14b615f/pubs/bibstruct.py#L10
should use `'ENTRYTYPE'` instead, just like bibtexparser. See https://github.com/sciunto-org/python-bibtexparser/pull/42 and https://github.com/sciunto-org/python-bibtexparser/pull/53.

**Comment by omangin** [comment]
Thanks @dotlambda  for reporting this. `type` is indeed a valid field name. (I am not sure `thesis` is a correct entry type, as far as I know `phdthesis` and `mastersthesis` were the sandard ones, but that does not matter here.)
