### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by dotlambda** [pubs/pubs#261]
I would love to see a new release of pubs. The last one is from 2019.

**Comment by benureau** [comment]
Yes. A release soon would be good. We will see if we switch the parser for pybtex before or after the next release (#255).

**Comment by omangin** [comment]
We have the pending [0.8.4 milestone](https://github.com/pubs/pubs/milestone/6). We can target that one soon. @benureau Should we include #255 as well or flag it for a follow up on a (to be created) 0.8.5?

**Comment by benureau** [comment]
Ok, after more than a year, release 0.9.0 is here (bump due to the number of improvements), and is available via pip. Closing this.
