### ISSUE TITLE
error: 'ENTRYTYPE' on lots of commands

### ISSUE THREAD

**Issue by rien333** [pubs/pubs#266]
A lot of `pubs` commands now just return `error: 'ENTRYTYPE'` for me. The errors seem to stem from specific papers,  perhaps papers I've added a while back. For instance:

```shell
# a paper I've recently added
$ pubs list citekey:progovac2020
[progovac2020] Benítez-Burraco, Antonio and Progovac, Ljiljana "A four-stage model for language evolution under the effects of human self-domestication" Language & Communication (2020) [pdf] | Language
# A paper I've added when I started using pubs (about a year ago?)
$ pubs list citekey:thompson2014
error: 'ENTRYTYPE'
```

Some more strange errors:

```shell
$ pubs list 
error: 'ENTRYTYPE'
$ pubs list year:2014
error: 'ENTRYTYPE'
# these commands works for some reasonn (cf. above)
$ pubs edit -m thompson2014
$ pubs tag thompson2014
```

Here is what  `~/.pubs` lists as metadata for a seemingly "faulty" entry:

```bibtex
bib/thompson2014.bib:
@book{thompson2014,
 author = {Thompson, Evan},
 title = {Waking, Dreaming, Being: Self and Consciousness in Neuroscience, Meditation, and Philosophy},
 publisher = {Columbia University Press},
 year = {2014},
 doi = {10.7312/thom13709}
}
```

``` yaml
# meta/thompson2014.yaml:
added: 2020-06-01 01:18:18.668669
docfile: /home/rw/Desktop/MetaAntro/paper/Thompson2014-ConsciousnessMeditation.pdf
tags: !!set
    Phenomenology: null
```

---

I'm using linux, python3.9, and a `pubs` build from git. `pubs` reports the following version:

```
$ pubs --version 
0.8.3
```

Let me know if I can provide more information.

**Comment by dotlambda** [comment]
I think I had the same error and solved it by deleting the cache (`~/.pubs/.cache`).

**Comment by rien333** [comment]
Ah right, that worked! Thanks.

Perhaps worth considering making the cache directory visible (I'm not sure how common it is to have hidden directories in hidden directories), or just putting it  in `~/.cache`.
