### ISSUE TITLE
Problem with math in titles

### ISSUE THREAD

**Issue by benureau** [pubs/pubs#29]
Bibtexparser is configured to convert accents into utf8. This has unfortunate side-effect on math in titles. The `\cup` is not preserved by bibtexparser. 

```
{Can the Measure of {$\cup^n_1 [ a_i , b_i ]$} be Computed in Less Than $\mathcal{O}(n \mathrm{log}n)$ Steps?}
```

**Comment by omangin** [comment]
This appears to have been solved by 3e3a67183753e.
