### ISSUE TITLE
Unpredictable tests

### ISSUE THREAD

**Issue by omangin** [pubs/pubs#40]
The following test fails from time to time in an (apparently) unpredictable manner.

The issue seems to come from the ordering of the elements in the dictionary. Needs more investigation…

```
FAIL: test_endecode_bibtex_editor (test_endecoder.TestEnDecode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pubs/pubs/tests/test_endecoder.py", line 68, in test_endecode_bibtex_editor
    self.assertEqual(bibraw1, bibraw2)
AssertionError: '@art[226 chars]n    volume = {59},\n    editor = {Feigenbaum,[33 chars]n}\n' != '@art[226 chars]n    editor = {Feigenbaum, Edward A. and Feldm[33 chars]n}\n'
  @article{turing1950computing,
      author = {Turing, Alan M},
      title = {Computing machinery and intelligence},
      journal = {Mind},
      publisher = {JSTOR},
      year = {1950},
      number = {236},
      pages = {433--460},
+     editor = {Feigenbaum, Edward A. and Feldman, Julian},
      volume = {59},
-     editor = {Feigenbaum, Edward A. and Feldman, Julian},
  }
```

**Comment by humm** [comment]
Yep, it's on my todo list. I'll write a better comparison function.

**Comment by omangin** [comment]
… or we can chose to make the output predictable by specifying a standard order for fields.

On thing we also have to do is to use [bibtex-parser's bwriter](https://github.com/sciunto-org/python-bibtexparser/blob/master/bibtexparser/bwriter.py) to encode the bibtex data. It has [an option](https://github.com/sciunto-org/python-bibtexparser/blob/master/bibtexparser/bwriter.py#L55) to order the keys in an entry that we could both expose to the user and use in the test to deal with this issue.

**Comment by humm** [comment]
Yep, I agree, we should close this and #33 at the same time.
