### ISSUE TITLE
info message for the ui

### ISSUE THREAD

**Issue by 73** [pubs/pubs#43]
I really like what you did with formatting. Which brings me to the current issue. I see:
```
warning: Provided citekey 'pag' has been autocompleted into 'page100'
```
with `warning` in yellow. I want to see:
```
info: Provided citekey 'pag' has been autocompleted into 'page100'
```
with `info` in green. In top of that I would change all questions to `warning`.
Is that okay with you @humm?    
--73

**Comment by humm** [comment]
Yes. You should add an info() method in PrintUI, which should seldom be used for possibly unexpected behaviour by pubs.

**Comment by 73** [comment]
Shouldn't it be:
+ *info*: Hey I took the liberty to do something for you (e.g. complete a key)
+ *waring*: Please pay attention now (e.g. Do you *really* want to delete that file?)
+ *error*: I'm sorry. Something *unexpected* happened and I'm not able to recover.
?
--73

**Comment by humm** [comment]
Let's not go all out *warring* now. :)

* Yes, exactly. It should appear infrequently in the user experience.
* The simple fact that we're asking for user input is enough to draw the user attention.
* Yes. So warning is for recoverable errors.
