### ISSUE TITLE
Improve color support

### ISSUE THREAD

**Issue by humm** [pubs/pubs#44]
**Current issues with colors:**

- [x] 'white' color
- [x] 256 color support
- [x] predefined themes
- [x] robust italics support (or remove italics)
- [x] `--force-colors` option
- [x] pager support

**Some remarks:**

- Italics have been removed as default. Reenabling them and verifying they work as intended is the responsability of the user. The `colors.sh` script can be used to diagnose problems.
- Need more predefined themes.
- Using White and Black is generally a bad idea. Using the default terminal color is usually better as it is robust to changes in the background color.

**Comment by 73** [comment]
I loose the colors when I pipe the output to a pager. Reproduce:
```
pubs list | less -r
```
`-r` should keep colors. But somehow it does not. My version of `less` is:
```
[$] less --version
less 481 (POSIX regular expressions)
....
```
It would be nice to be able to keep the colors on a pager.      
--73

**Comment by humm** [comment]
This is by design, so that when piping to a file, the text is written without colors.

But in some instances such as yours, it would be useful. I will add an argument `--force-colors` or a config option.

**Comment by 73** [comment]
Jeah. That would be nice. Idealy list would use a pager like git log. But
haven't talked to you guys about that, yet and it seems rather
intrusive.
--73

**Comment by 73** [comment]
Would it make sense to distinguish between a *pipe* and a *redirection*? Imho users redirect output to a file and pipe to another process. See: https://stackoverflow.com/questions/13442574/how-do-i-determine-if-sys-stdin-is-redirected-from-a-file-vs-piped-from-another      
--73

**Comment by humm** [comment]
Thanks for the links, I did not know you could tell the difference from inside python. But making the difference does not really help: `pubs list | less` needs to work out-of-the-box, and as shown by `pubs list --force-colors | less`, it would not if we kept colors for redirections by default.

**Comment by 73** [comment]
Thats bad. I looked good though...
