### ISSUE TITLE
list should support a pager

### ISSUE THREAD

**Issue by 73** [pubs/pubs#47]
Hi, 
I would like to discuss the idea of defaulting the `list` to a pager. It the user wants to redirect to a file he should use `export`. If we agree on that, this would mean two changes:
1. Introduce a pager to list.
2. Extend the export to support the same queries as list das does.
    2.1 Extract a query processor and use it for both commands.
What do you think guys?
--73

**Comment by humm** [comment]
I do think that if you want to use a pager with pubs, using the alias plugin is perfect (see readme for examples), does not require more code, and will be colourful as soon as I implement the --force-colors option.

I am closing this for now, do reopen if you do not agree.

**Comment by humm** [comment]
@73: Done. `pubs --force-colors list | less -r` now works as you would except. You can create an alias in the configuration.

**Comment by 73** [comment]
added the following alias:
```ini
[[alias]]
# new subcommands can be defined, e.g.:
# print = open --with lp
# evince = open --with evince
ls = !pubs --force-colors list | less

# shell commands can also be defined, by prefixing them with a bang `!`, e.g:
# count = !pubs list -k | wc -l
```
But `pubs ls` throws an error. Can you check? 
--73

**Comment by humm** [comment]
Ok, I am gonna need a little more details...

**Comment by 73** [comment]
Oh shoot, I just realize I have to activate the `alias`plugin right? The `readme.md` does not say so. Should be updated.

**Comment by 73** [comment]
It works. Thx.

**Comment by humm** [comment]
No problem.
