### ISSUE TITLE
Feature Request: Enable more than one template

### ISSUE THREAD

**Issue by minthemiddle** [pubs/pubs#55]
Right now, `Pubs` ships with one article template when generating a blank entry. As not all entries come via DOI or ISBN (and hence would get an auto entry) but your sources my always be the same, such as `web` and `book`, it would be handy to add entries with various templates.

The command could be something like `pubs add -t book` for a `book.py/bib` template.

**Comment by humm** [comment]
That should be easy to do. Adding it to the list!
