### ISSUE TITLE
Submit to PyPi (so you can install via pip)

### ISSUE THREAD

**Issue by minthemiddle** [pubs/pubs#56]
Right now I need to manually install `pubs` via `python setup.py install`. When working with virtualenvs and different versions of Python (and actually in general), managing Python packages with `pip` - hence `pip install pubs` would be the the preferred solution. There is a [handy description](https://packaging.python.org/distributing/#uploading-your-project-to-pypi) for project maintainers on how to do that.

It would be great if `pubs` was available via `pip`.

**Comment by humm** [comment]
Indeed. Actually you can already do `pip install pubs`, but the version is not up-to-date. I'll do some clean-up on the code in the next days (some tests are not passing anymore), and I'll release a new version.

**Comment by humm** [comment]
By the way, you can already use pip! With any github repo. Just do:
`pip install --upgrade git+https://github.com/pubs/pubs`

**Comment by minthemiddle** [comment]
Ah, cool. I just tried the casual via `pip` on Windows and OSX with Python 3.5. Here is the error message:

```
(venv-pubs)bash-3.2$ pip install pubs
Collecting pubs
  Could not find a version that satisfies the requirement pubs (from versions: )
No matching distribution found for pubs
```

But hey, that is no surprise any longer :)

**Comment by beuerle** [comment]
For people running Arch Linux, there's an AUR package available:

https://aur.archlinux.org/packages/pubs-git/

Maybe add that to an installation section in the README?

**Comment by omangin** [comment]
With the merge of #82, we should be good for the version update and the new upload to pypi!

**Comment by alecive** [comment]
Why not using travis to submit to pypi after every push and test passes?

**Comment by benureau** [comment]
@alecive: That's an interesting proposition. We'll probably submit this one to PyPi manually, and look over what need to be done to use travis this way. I am not sure the tests are up to par for this yet.
@omangin: I agree. Should you or should I?

**Comment by omangin** [comment]
@benureau You're the owner of the Pypi package, so I'll let you do it. I've created a PR (#83) with some minor updates to validate before updating to 0.7.0. You'll also need to create a tag after merging.

@alecive That's a good idea but should only happen after version updates so I'm not sure Travis should take care of it. Also, I'm not sure that's feasible without exposing credentials publicly.

**Comment by alecive** [comment]
I am pretty sure you can create specific travis rules that are executed only when a new tag/release is pushed to master. I didn't dig into it, but you can already specify rules that e.g. work only on master or on pull requests, so it makes sense to me if there are options only for tags.

**Comment by omangin** [comment]
Indeed: https://docs.travis-ci.com/user/deployment/pypi/. And they have an option to encrypt the password. I'm however not 100% sure it really worth the effort compared to `python setup.py sdist upload -r pypi`…

**Comment by alecive** [comment]
Sure, but you know how much I love to spread the travis and CI verb everywhere :sunglasses:
