### ISSUE TITLE
Cannot edit conf

### ISSUE THREAD

**Issue by minthemiddle** [pubs/pubs#57]
When running `pubs conf` (both as user and root in a virtualenv, latest Win and OSX), I get an error message:

`error: [Errno 13] Permission denied`

**Comment by humm** [comment]
Hum... your conf file should be located at `~/.pubsrc`. Can you edit it directly, with, for instance `vim ~/.pubsrc`? By the way, we tested pubs on OSX and Linux, but never on Windows. You may get strange issues there.

**Comment by omangin** [comment]
I assume this was fixed at the same time as #63. Please reopen if still an issue.
