### ISSUE TITLE
Broken tests for python2

### ISSUE THREAD

**Issue by omangin** [pubs/pubs#58]
The use of open instead of io.open breaks the compatibility with python2.

**Comment by benureau** [comment]
Ok, so I upgraded pyfakefs from 2.8 to 3.3(dev) and some work was needed to make our test suite work again (see [bug/unittests](/pubs/pubs/tree/bug/unittests)). I'll be attacking the compatibility with Python 2 next.

**Comment by benureau** [comment]
Resolved with #73
