### ISSUE TITLE
websearch fails for python3

### ISSUE THREAD

**Issue by beuerle** [pubs/pubs#69]
If run with `python3` the `websearch` command fails:

```bash
$ python --version
Python 3.6.1
$ pubs websearch <string>
error: module 'urllib' has no attribute 'quote_plus'
```

`urllib` has been split up into different subpackages, and the `quote_plus` function is now in `urllib.parse`. Thus `urllib.quote_plus` has to be changed to `urllib.parse.quote_plus` in `websearch_cmd.py`, however this will break `python2` compatibility?

**Comment by benureau** [comment]
@beuerle: Thanks for the issue report. We plan to drop support for Python 2, but not right now. So we'll write two code with `try catch` statements around the import. I am putting this problem at the top of the todo list.
