### ISSUE TITLE
allow different file extension for note files

### ISSUE THREAD

**Issue by beuerle** [pubs/pubs#70]
The file extension for note files is so far hard-coded as `txt`. Although the use of any markup language in a note is possible, editors would use syntax highlighting i.e. for markdown automatically when the file extension is `mkd` and command `pubs note citekey` is called. The file extension could maybe be set in the config file?

**Comment by omangin** [comment]
Yes, that's an issue and using a configuration entry probably is the simplest way to handle it. So I'll start with this one.

On the long run, it would be better to also support changing the file type in the command line to handle other kinds of notes (e.g. pdf scans).

**Comment by beuerle** [comment]
@omangin: thanks for the quick implementation!

> On the long run, it would be better to also support changing the file type in the command line to handle other kinds of notes (e.g. pdf scans).

I agree. but for this to make sense a bigger overhaul of the _note architecture_ would be necessary, as so far one reference gets associated with one notes file by the citekey.

Additionally, as I am new to pubs: there's currently no way to _dump_ the notes file to the terminal, is there? Something like

```bash
$ pubs note show citekey
- what a great paper that is
- ...
```

If you just want to access the notes file itself, it's not that important. But if you write your notes i.e. in markdown, you could either pipe the output of this to a terminal markdown viewer or directly to pandoc to easily convert it to other formats.

**Comment by omangin** [comment]
Yes, that's true. One of the reasons the note are not fully implemented is that we initially intended to support them through a plugin. I believe that was the reason for #9. There is kind of a repetitive pattern in the way docs and notes are handled but until there really is the need for other kinds of attachements we can stick with having notes as a core command.

What should have been done was to add sub-commands for notes, the same way docs are handled except that there would be an `edit` command for notes. That way dumping the notes would be possible from a simple `pubs doc open -w cat <citekey>`. The idea is then that user specific behaviors (like piping to Pandoc) are easy to customize with the `alias` plugin.

The first steps for that should be the following:

- [ ] it seems that note paths are not correctly expanded (when `~` in them), to check and fix,
- [ ] store note attachments in the metadata, (should we support several note files for one paper?)
- [ ] add and implement sub-commands for notes `add`, `edit`, `open`, `remove`,
- [ ] implement migration to track note files from older repositories that do not register notes in metadata.

**Comment by beuerle** [comment]
> Yes, that's true. One of the reasons the note are not fully 
> implemented is that we initially intended to support them through a 
> plugin. I believe that was the reason for #9. There is kind of a 
> repetitive pattern in the way docs and notes are handled but until 
> there really is the need for other kinds of attachements we can stick 
> with having notes as a core command.

I haven't had the time yet to actually dig into the code to fully understand how you set pubs up, so I have no opinion on whether it would be necessary to implement this feature as a plugin.


> What should have been done was to add sub-commands for notes, the same 
> way docs are handled except that there would be an edit command for 
> notes. That way dumping the notes would be possible from a simple pubs 
> doc open -w cat <citekey>. The idea is then that user specific 
> behaviors (like piping to Pandoc) are easy to customize with the alias 
> plugin.

Yes, sub-commands would be necessary. Otherwise the functionality of `pubs note` would stay very rudimentary (might be a feature?). I think this would be very beneficial and could be implemented rather easily.


> * store note attachments in the metadata, (should we support several 
>   note files for one paper?)

As for actual _notes_, I don't know if it would be necessary to allow more than one file. One way would be to only allow one _plain text note_ file, but multiple additional attached documents (scanned PDFs, additional documents, whatever ...). pubs could display all attached documents via `pubs note list <citekey>`.

**Comment by omangin** [comment]
I'll move the improvements on the note command to another pull request.

**Comment by omangin** [comment]
> As for actual notes, I don't know if it would be necessary to allow more than one file. One way would be to only allow one plain text note file, but multiple additional attached documents (scanned PDFs, additional documents, whatever ...). pubs could display all attached documents via `pubs note list <citekey>`.

This is what #9 was about.
