### ISSUE TITLE
Cannot add DOI because "error: 'ascii' codec can't encode character ..."

### ISSUE THREAD

**Issue by eschen42** [pubs/pubs#76]
I installed pubs with
```
pip install --upgrade git+https://github.com/pubs/pubs
```
Should the `--upgrade` switch have been included in the instructions on the README.md page?

I have a DOI that apparently pubs add is allergic to (another DOI added fine):
```
$ pubs add -D 10.1021/ac0713510
error: 'ascii' codec can't encode character u'\xf6' in position 80: ordinal not in range(128)
```
One of the authors is named `Sjöström`; position 80 is that of the first vowel in this name.

After this, 
```./bib/Wiklund_2008.bib```
exists with zero size, and I cannot use
```pubs remove Wiklund_2008```
to get rid of it; hence, if I keep trying I accumulate Wiklund_2008.bib, Wiklund_2008a.bib, Wiklund_2008b.bib, Wiklund_2008c.bib etc., all with zero size.

I tried to help myself without success:
```
$ pubs conf
error: edit_file() takes exactly 3 arguments (2 given)
```

I gather from [issue 51](https://github.com/pubs/pubs/issues/51) that I  need to install the `utf-8` codec
but I do not see instructions regarding how to do so.

**Comment by benureau** [comment]
Thanks for the issue!

The `--upgrade` is needed if you already installed `pubs`, to get the lasted version.

I was able to reproduce your bug. It appears only with Python 2, with Python 3 you don't have the problem. But switching to python 3 might not be an option for you. 

I will attend the bug, but not before Friday, unless @omangin gets to it first.

**Comment by eschen42** [comment]
Awesome. Thank you.

**Comment by omangin** [comment]
Thanks @eschen42 for the notice.

There were actually several issues here.

- an actual bug on writing non-ascii content from python 2 (which ended up leaving an empty file as you told),

- this error was not caught by the `add` command,

- the remove command does not work when there is no metadata for the paper. This comes from the fact that we use metadata files as the source for the citekeys in the repository. Hence the `add` command failing to write the metadata file, the repository was in a broken state. This specific case could be solved by switching the following lines in the `remove` method from the repository:
  ````
   self.citekeys.remove(citekey)
   self.databroker.remove(citekey)
   ````
  We could also check if the citekey exists in the repository, raise a warning if not and proceed to remove it anyway. I'm however not in favor of this, and I would rather implement some repository sanity check instead with some command to interactively clean "orphaned" bib files or create metadata files for them. Any comment?

I've only fixed the bug but maybe we should also take care of the others (eventually in separate issues). See #77 for the fix.

**Comment by benureau** [comment]
Thanks @omangin for these explanations. Yes, a `pubs doctor` might make sense. But we should also strive to act on the user intent: if he wants to remove a paper or a citekey, he might not care much about the rest of the repository (let's say he is on a deadline or something): a warning, a demand for a confirmation and a suggestion to run `pubs doctor` might be best.

**Comment by omangin** [comment]
> Yes, a pubs doctor might make sense. But we should also strive to act on the user intent: if he wants to remove a paper or a citekey, he might not care much about the rest of the repository (let's say he is on a deadline or something): a warning, a demand for a confirmation and a suggestion to run pubs doctor might be best.

Yes, that what I had in mind with having separate commands for checking and cleaning.
