### ISSUE TITLE
pubs conf confusion

### ISSUE THREAD

**Issue by eschen42** [pubs/pubs#84]
I don't know how to edit `~/.pubsrc` except directly. Here's what happens when I try to use `pubs conf`:
```bash
~/.pubs$ pubs conf
error: edit_file() takes exactly 3 arguments (2 given)
~/.pubs$ pubs conf ~/.pubsrc
usage: pubs [-h] [--version]
            {init,conf,add,rename,remove,list,doc,tag,note,export,import,websearch,edit}
            ...
pubs: error: unrecognized arguments: /home/art/.pubsrc
~/.pubs$ pubs conf -h
usage: pubs conf [-h]

optional arguments:
  -h, --help  show this help message and exit
~/.pubs$ python -V
Python 2.7.13
```
Is this an issue, or am I just doing something wrong?

Thank you for pubs - it's life-changing!

**Comment by omangin** [comment]
Hi @eschen42. Thank you for your comment. We're glad you like pubs!

This is indeed a bug that we recently fixed with #82. Updating pubs to the latest git version should fix it (or to version 0.7.0 when it's out).

Please re-open you still experience the issue.
