### ISSUE TITLE
More robust pubs list

### ISSUE THREAD

**Issue by benureau** [pubs/pubs#87]
`list` command code needs to be more robust in case one or more bibdata entry are unreadable. I had one bib file empty, and I got
```
$ pubs list
error: could not parse provided bibdata:

$ 
```

**Comment by omangin** [comment]
To come back to this topic, I'm not sure `pubs` should be robust to this: an empty bibtex is not a correct bibtex and repository being bibtex based, that something that should be at least notified. I'm fine with assuming that the repository is always in a sane state and failing when it's not.

What the code should, however, do here, is to provide a better message that includes the erroneous citekey. Internally, we probably want to use a dedicated exception to for this situation.

**Comment by pmarkaide** [comment]
If I can add to the discussion, at very least pubs should avoid adding bib entries without citekeys as a minimal field.

I can add this without an error or even warning:

```
@article{,
    author = {Conover, Robert J},
    title = {Assimilation of organic matter by zooplankton},
    journal = {Limnology and oceanography},
    publisher = {Wiley Online Library},
    year = {1966},
    number = {3},
    volume = {11},
    pages = {338--345},
}
#not ussual but I've found this type of bibs in google scholar :$
#this is made for example
```
And later is not easy to remove an entry _without_ citekey (I solve it with `pubs remove ' '`)

Other fields can be all optional or set warnings for some basics like year, author, journal as will be false negative result in (common) searches

**Comment by omangin** [comment]
Thanks @pmarkaide. That's indeed a bug that needs to be fixed. I'll add a new issue for that.

**Comment by benureau** [comment]
@omangin: by robust I mean that if a bibentry is unreadable, the repository should isolate it, warn the user, and display the other entries. It could be something like:
`warning: bibentry 'citekey' could not be parsed. It is advised to run 'pubs doctor'.`
The repository should continue to work with all the valid bibentries. In other words, it should fail gracefully.

**Comment by omangin** [comment]
@pmarkaide  Can you have a look at my comment on #113?

@benureau That's what I understood. My point was to take an alternative, more extreme approach: display an error instead of the warning. This was partially because `pubs doctor` does not exist yet, so I'd rather enforce that the repository is fixed early (for instance with `pubs edit <citekey>`. Although the other approach is fine too.
