### ISSUE TITLE
"pubs list" has different behavior in custom commands than in terminal

### ISSUE THREAD

**Issue by amartos** [pubs/pubs#88]
In a terminal, if you use the command `pubs list -k abstract:"Only a few genes remain"` to retrieve the key corresponding to the article `doi:10.1371/journal.pgen.1002876`, it indeed outputs you the right key.

However, if you define the command `exportlist = !pubs list -k "$@"` in the conf file and try `pubs exportlist abstract:"Only a few genes remain"`, the output is `error: Invalid query (a)`.

**Comment by omangin** [comment]
Thanks @amartos. That's indeed a bug of the alias plugin. The argument escaping seems to be broken while calling the shell. I'll look at it.
