### ISSUE TITLE
Print help on when no subcommands are supplied

### ISSUE THREAD

**Issue by wflynny** [pubs/pubs#99]
When attempting to use a less-often-used command, it'd be nice if `pubs` printed the main parser help.  For example, this is how the git CLI works.  Are the maintainers open to this behavior?  I've got a [commit on a fork](https://github.com/pubs/pubs/compare/master...wflynny:help-when-no-subcommand) that does just this.

**Comment by omangin** [comment]
Yes, that makes sense to me. Can you create a pull request for your commit? Also the unit test you removed should be instead updated to check for the expected behavior.

Thanks @wflynny!
